### PR TITLE
Added Testing using Jest

### PR DESCRIPTION
**Pull request by michaeldera**
I changed the way the code is organised that added tests using Jest into the project. I separated some of the classes so I could implement tests to each of the classes separately. Also fixed an issue where totals were not actually returning from the payment class. 

### To run tests 

- Clone repo into your local environment 
- Run `npm install` from the command line 
- Then run `npm test` or `jest` to run tests

### CODE REVIEW

**Comment by melmups** [comment]
Hi Micheal. Can you please reopen this PR but into the develop branch and not the master branch

**Comment by melmups** [comment]
alt text

Heads up. Your tests were erroring out. You might also want to look into that

**Comment by melmups** [comment]
One final thing. Can you please pull the changes from paynow:develop into your local branch before you submit the PR. There are some bug fixes that had been added after you submitted the PR.

Trying to avoid having to cherry pick through the commit

**Comment by melmups** [comment]
> One final thing. Can you please pull the changes from paynow:develop into your local branch before you submit the PR. There are some bug fixes that had been added after you submitted the PR.
> 
> Trying to avoid having to cherry pick through the commit

Noticed you already submitted the PR. Don't worry about it. I'll add those in

**Comment by michaeldera** [comment]
Alright..... will have to do this a little later 

> alt text
> 
> Heads up. Your tests were erroring out. You might also want to look into that

My bad. I did test everything before I put it out.... Will go over it again. I think it may be due to the fact that the versions of the packages are not locked and may have changed since I did the PR. I will look into it in the evening and redo it.

**Comment by michaeldera** [comment]
> > One final thing. Can you please pull the changes from paynow:develop into your local branch before you submit the PR. There are some bug fixes that had been added after you submitted the PR.
> > Trying to avoid having to cherry pick through the commit
> 
> Noticed you already submitted the PR. Don't worry about it. I'll add those in

Great! Thank you

**Pull request merged**
